version: '3.8'
services:
  web:
    image: ruiznorlan/odoo:15.0
    container_name: odoo_production
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: ruiznorlan/postgres:14
    container_name: postgres_production
    command: ["postgres", "-c", "config_file=/etc/postgres.conf"]
    environment:
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: